  - hosts: cluster
    roles:
      - cluster
    vars:

     # Hosts
     node01: 'node01'
     node02: 'node02'

     # MySQL users
     mysql_replication_user: 'replicator'
     mysql_replication_password: '4iSE2qZNOwu2eWdcUO3m'
     mysql_replication_host: '%'

     mysql_root_user: 'root'
     mysql_root_password: '4iSE2qZNOwu2eWdcUO3m'
     mysql_root_host: 'localhost'

     mysql_wordpress_user: 'wpuser'
     mysql_wordpress_host: 'localhost'
     mysql_wordpress_password: '4iSE2qZNOwu2eWdcUO3m'
     mysql_wordpress_database: 'wpbase'
     
     # Linux
     selinux_state: 'permissive'

     # Pacemaker
     pacemaker_cluster_name: 'hacluster'
     pacemaker_user: 'pacemaker'
     pacemaker_password: 'oET3lvliC0Btqm4h7zfn'
     stonith_status: 'false'
     stickiness: '100'
     quorum_policy: 'ignore'

     # ClusterIP
     ip: '192.168.100.100'
     ip_netmask: '32'
     ip_int: '5'

     # Nginx
     nginx_int: '5'

     # Php-fpm
     fpm_int: '5'

     # Lsyncd
     lsyncd_int: '5'
