---
  - name: check availability databases
    stat: path=/root/databases.already.import
    register: databases_status

  - name: create databases
    mysql_db:
     name: "{{ wordpress_database }}"
     collation: "utf8_general_ci"
     encoding: "utf8"
     state: "present"
    when: databases_status.stat.exists == false

  - name: set databases status 'already'
    file: path=/root/databases.already.import state=touch owner=root group=root mode=0600
