---
  - name: install epel repo
    yum: name=epel-release

  - name: add nginx repository
    yum_repository:
     name: nginx repo
     description: nginx repo
     baseurl: http://nginx.org/packages/centos/7/$basearch/

  - name: upgrade all packages
    yum: name=* state=latest

  - name: install recommended packages
    yum: name={{ item }}
    with_items:
    - libselinux-python
    - policycoreutils-python
    - nano
    - bash-completion
    - net-tools
    - wget
    - curl
    - lsof
    - tcpdump
    - telnet
    - nmap
    - nc
    - htop
    - mc
    - ntp
    - rsync
    - mlocate
    - pacemaker 
    - pcs
    - psmisc
    - mariadb-server
    - MySQL-python
    - nginx
    - php-fpm

  - name: selinux -> permissive
    selinux: policy=targeted state={{ selinux_state }}

  - name: upload config mariadb
    template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root
    notify:
    - restart mariadb

  - name: copy .my.cnf file with root password credentials
    template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: enable and start mariadb/pcs service
    service: name={{ item }} enabled=yes state=started
    with_items:
    - mariadb
    - pcsd

  - name: change pacemaker password
    user: name={{ pacemaker_user }} password={{ pacemaker_password | password_hash( 'sha512', ansible_hostname ) }}

  - name: setup mysql users
    include: users.yml

  - name: setup node01
    include: node01.yml
    when: ansible_hostname == "{{ node01 }}"

  - name: setup node02
    include: node02.yml
    when: ansible_hostname == "{{ node02 }}"

  - name: setup databases
    include: databases.yml
    when: ansible_hostname == "{{ node01 }}"
