---
  - name: install epel repo
    yum: name=epel-release

  - name: install needed packages
    yum: name={{ item }}
    with_items:
    - libselinux-python
    - policycoreutils-python
    - pacemaker
    - pcs
    - psmisc
    - mariadb-server
    - MySQL-python
    - nginx
    - php-fpm
    - lsyncd

  - name: install additional packages
    yum: name={{ item }}
    with_items:
    - nano
    - bash-completion
    - net-tools
    - wget
    - curl
    - lsof
    - tcpdump
    - telnet
    - nmap
    - nc
    - htop
    - mc
    - ntp
    - rsync
    - mlocate

  - name: selinux -> permissive
    selinux: policy=targeted state={{ selinux_state }}

  - name: upload config mariadb
    template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root
    notify:
    - restart mariadb

  - name: upload config lsyncd
    template: src=lsyncd.conf.j2 dest=/etc/lsyncd.conf owner=root group=root
    notify:
    - restart lsyncd

  - name: create lsyncd log directory
    file: path=/var/log/lsyncd state=directory mode=0755

#  - name: copy .my.cnf file with root password credentials
#    template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: enable and start mariadb/pcs service
    service: name={{ item }} enabled=yes state=started
    with_items:
    - mariadb
    - pcsd
    - lsyncd

  - name: change pacemaker password
    user: name={{ pacemaker_user }} password={{ pacemaker_password | password_hash( 'sha512', ansible_hostname ) }}

  - name: setup mysql users
    include: users.yml

  - name: setup node01
    include: node01.yml
    when: ansible_hostname == "{{ node01 }}"

  - name: setup node02
    include: node02.yml
    when: ansible_hostname == "{{ node02 }}"

  - name: setup mysql databases
    include: databases.yml
    when: ansible_hostname == "{{ node01 }}"
