---
  - name: install epel repo
    yum: name=epel-release

  - name: upgrade all packages
    yum: name=* state=latest

  - name: install recommended packages
    yum: name={{ item }}
    with_items:
    - libselinux-python
    - policycoreutils-python
    - nano
    - bash-completion
    - net-tools
    - wget
    - curl
    - lsof
    - tcpdump
    - telnet
    - nmap
    - nc
    - htop
    - mc
    - ntp
    - rsync
    - mlocate
    - pacemaker 
    - pcs
    - psmisc
    - mariadb-server
    - MySQL-python

  - name: selinux -> permissive
    selinux: policy=targeted state={{ selinux_state }}

  - name: upload config mariadb
    template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root
    notify:
    - restart mariadb

  - name: copy .my.cnf file with root password credentials
    template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: enable and start mariadb/pcs service
    service: name={{ item }} enabled=yes state=started
    with_items:
    - mariadb
    - pcsd

  - name: change pacemaker password
    user: name={{ pacemaker_user }} password={{ pacemaker_password | password_hash( 'sha512', ansible_hostname ) }}

  - name: update mysql root password
    mysql_user: 
     name: "{{ mysql_root_user }}"
     hosts:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
     password: "{{ mysql_root_password }}"
     login_user: "{{ mysql_root_user }}"
     login_password: "{{ mysql_root_password }}"
     check_implicit_admin: "yes" 
     priv: "*.*:ALL,GRANT" 
     state: "present"

  - name: add mysql user replicator
    mysql_user:
     name: "{{ mysql_replication_user }}"
     host: "{{ mysql_replication_host }}"
     password: "{{ mysql_replication_password }}"
     priv: "*.*:replication slave"
     state: "present"

  - name: setup node01
    include: node01.yml
    when: ansible_hostname == "{{ node01 }}"

  - name: setup node02
    include: node02.yml
    when: ansible_hostname == "{{ node02 }}"

  - name: setup databases
    include: databases.yml
    when: ansible_hostname == "{{ node01 }}"

  - name: setup users
    include: users.yml
