---
  - name: check pacemaker status
    stat: path=/root/pacemaker.already.setup
    register: pacemaker_status

  - name: authenticate all nodes
    command: pcs cluster auth {{ node01 }} {{ node02 }} -u {{ pacemaker_user }} -p {{ pacemaker_password }}
    when: pacemaker_status.stat.exists == false

  - name: setup cluster message bus
    command: pcs cluster setup --name {{ pacemaker_cluster_name }} {{ node01 }} {{ node02 }}
    when: pacemaker_status.stat.exists == false

  - name: start all cluster nodes
    command: pcs cluster start --all
    when: pacemaker_status.stat.exists == false

  - name: enable the cluster on all nodes
    command: pcs cluster enable --all
    when: pacemaker_status.stat.exists == false

  - name: set default resource stickiness
    command: pcs resource defaults resource-stickiness={{ stickiness }}
    when: pacemaker_status.stat.exists == false

  - name: set stonith status
    command: pcs property set stonith-enabled={{ stonith_status }}
    when: pacemaker_status.stat.exists == false

  - name: set quorum policy
    command: pcs property set no-quorum-policy={{ quorum_policy }}
    when: pacemaker_status.stat.exists == false

  - name: create resource ClusterIP
    command: pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip={{ ip }} cidr_netmask={{ ip_netmask }} op monitor interval={{ ip_int }}s
    when: pacemaker_status.stat.exists == false

  - name: create resource Nginx
    command: pcs resource create Nginx systemd:nginx op monitor interval={{ nginx_int }}s
    when: pacemaker_status.stat.exists == false

  - name: create resource Php-fpm
    command: pcs resource create Php-fpm systemd:php-fpm op monitor interval={{ fpm_int }}s
    when: pacemaker_status.stat.exists == false

  - name: create resource Lsyncd
    command: pcs resource create Lsyncd systemd:lsyncd op monitor interval={{ lsyncd_int }}s
    when: pacemaker_status.stat.exists == false

  - name: create Web group
    command: pcs resource group add Web Nginx Php-fpm Lsyncd
    when: pacemaker_status.stat.exists == false

  - name: setup colocation
    command: pcs constraint colocation add Web with ClusterIP INFINITY
    when: pacemaker_status.stat.exists == false

  - name: setup order
    command: pcs constraint order ClusterIP then Web
    when: pacemaker_status.stat.exists == false

  - name: set pacemaker status 'already'
    file: path=/root/pacemaker.already.setup state=touch owner=root group=root mode=0600

  - name: Get Slave Status
    mysql_replication: master_user={{ mysql_replication_user }} master_password={{ mysql_replication_password }} mode=getslave 
    register: slave_status
    ignore_errors: true

  - name: Stop Slave
    mysql_replication: master_user={{ mysql_replication_user }} master_password={{ mysql_replication_password }} mode=stopslave
    when: slave_status|failed or slave_status.Slave_SQL_Running != "Yes"

  - name: Get Master Status
    mysql_replication: master_user={{ mysql_replication_user }} master_password={{ mysql_replication_password }} mode=getmaster
    register: master_status
    ignore_errors: true

  - name: Resync with Master 
    mysql_replication: master_user={{ mysql_replication_user }} master_password={{ mysql_replication_password }} mode=changemaster master_host={{ node02 }} master_log_file={{ master_status.File }} master_log_pos={{ master_status.Position }}
    when: slave_status|failed or slave_status.Slave_SQL_Running != "Yes" 

  - name: Start Slave after resync
    mysql_replication: master_user={{ mysql_replication_user }} master_password={{ mysql_replication_password }} mode=startslave
    when: slave_status|failed or slave_status.Slave_SQL_Running != "Yes"
