---
# wordpress
  - name: add or update mysql user wordpress
    mysql_user:
     name: "{{ mysql_wordpress_user }}"
     host: "{{ mysql_wordpress_host }}"
     password: "{{ mysql_wordpress_password }}"
     login_user: "{{ mysql_root_user }}"
     login_password: "{{ mysql_root_password }}"
     check_implicit_admin: yes
     append_privs: yes
     priv: "{{ mysql_wordpress_database }}.*:ALL,GRANT"
