---
  - name: update mysql root password
    mysql_user: 
     name: "{{ mysql_root_user }}"
     hosts:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
     password: "{{ mysql_root_password }}"
     priv: "*.*:ALL,GRANT" 
     state: "present"
     login_user: "{{ mysql_root_user }}"
     login_password: "{{ mysql_root_password }}"
     check_implicit_admin: "yes"

  - name: add mysql user replicator
    mysql_user:
     name: "{{ mysql_replication_user }}"
     host: "{{ mysql_replication_host }}"
     password: "{{ mysql_replication_password }}"
     priv: "*.*:replication slave"
     state: "present"
     login_user: "{{ mysql_root_user }}"
     login_password: "{{ mysql_root_password }}"
     check_implicit_admin: "yes"

  - name: add or update mysql user wordpress
    mysql_user:
     name: "{{ mysql_wordpress_user }}"
     host: "{{ mysql_wordpress_host }}"
     password: "{{ mysql_wordpress_password }}"
     priv: "{{ mysql_wordpress_database }}.*:ALL,GRANT"
     state: "present"
     login_user: "{{ mysql_root_user }}"
     login_password: "{{ mysql_root_password }}"
     check_implicit_admin: "yes"

