---
  - name: add or update mysql user wordpress
    mysql_user:
     name: "{{ mysql_wordpress_user }}"
     host: "{{ mysql_wordpress_host }}"
     password: "{{ mysql_wordpress_password }}"
     priv: "{{ mysql_wordpress_database }}.*:ALL,GRANT"
     state: "present"
